module Activesupport
  module Logger
    VERSION: String
    # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  end
end
module ActiveSupport
  module Version
    VERSION: String
  end
  VERSION: String
end
