module Activesupport
  module Logger
    VERSION: String
    module Version
      VERSION: String
    end
    # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  end
end

module ActiveSupport
  module Version
    VERSION: String
  end
  VERSION: String
  module Logger
    module SimpleFormatter
      module Version
        VERSION: String
      end
      VERSION: String
    end
  end

  module LoggerVersion
    VERSION: String
  end
end
